rel:
	@cd vio; make
	@cd venc; make
	@cd audio; make
	@cd wifi_sta_8801; make
clean:
	@cd vio; make clean
	@cd venc; make clean
	@cd audio; make clean
	@cd wifi_sta_8801; make clean;
cleanall:
	@cd venc; make cleanall
	@cd audio; make cleanall
	@cd audio_AAC; make cleanall
	
