.PHONY:all sensor audioonly2fae audioinner

all: sensor 

sensor:
	@cd sensor; make
	
audioinner:
	@cd audio/inner; make
	
audioonly2fae:
	@cd audio/only2fae; make

clean:
	@cd sensor; make clean
	@cd audio/inner; make clean
	@cd audio/only2fae; make clean
