.PHONY:all sensor audioaac gyro

all:audioaac 

sensor:
	@cd sensor; make
	
audioaac:
	@cd audio/aac; make

gyro:
	@cd gyro; make

clean:
	#@cd sensor; make clean
	@cd audio/aac; make clean
	@cd gyro; make clean
